#!/bin/sh
################################################################################
#                                                                              #
# blackarch-installer - Simple installer for BlackArch Linux                   #
#                                                                              #
# FILE                                                                         #
# blackarch-install                                                            #
#                                                                              #
# DATE                                                                         #
# 2016-04-11                                                                   #
#                                                                              #
# DESCRIPTION                                                                  #
# Simple Installer for BlackArch Linux                                         #
#                                                                              #
# AUTHOR                                                                       #
# noptrix@nullsecurity.net                                                     #
#                                                                              #
################################################################################

source "$(pwd)/lib/blackarch.sh"


# controller and program flow
main()
{
    clear
    check_uid
    check_env

    # install mode
    ask_install_mode

    # keymap
    ask_keymap
    set_keymap
    clear

    # network
    ask_hostname
    if [ \
        "${INSTALL_MODE}" = ${INSTALL_REPO} -o \
        "${INSTALL_MODE}" = ${INSTALL_BLACKMAN} ]
    then
        get_net_ifs
        ask_net_if
        ask_net_conf_mode
        case "${NET_CONF_MODE}" in
            "${NET_CONF_AUTO}")
                net_conf_auto
                ;;
            "${NET_CONF_MANUAL}")
                ask_net_addr
                net_conf_manual
                ;;
            "${NET_CONF_SKIP}")
                break
                ;;
            *)
                ;;
        esac
        sleep_clear 1
        check_inet_conn
        sleep_clear 1
    fi

    # pacman
    update_pacman_conf
    sleep_clear 1

    # hard drive
    get_hd_devs
    ask_hd_dev
    umount_filesystems "harddrive"
    sleep_clear 1
    ask_cfdisk
    sleep_clear 1
    ask_luks
    get_partition_label
    get_partitions
    print_partitions
    ask_formatting
    clear
    make_partitions
    clear
    mount_filesystems
    sleep_clear 1

    # arch linux
    install_base_packages
    sleep_clear 1
    setup_base_system
    sleep_clear 1

    # blackarch Linux
    setup_blackarch
    sleep_clear 1

    # epilog
    umount_filesystems
    sleep_clear 1
    sync_disk
    sleep_clear 1
    easter_backdoor

    return $SUCCESS
}


# we start here
main "${@}"


# EOF
